"""add_price_bars

Revision ID: 7f5abe150d86
Revises: 912506af2bea
Create Date: 2026-06-23 19:11:40.500109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7f5abe150d86'
down_revision: Union[str, None] = '912506af2bea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_bars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=12), nullable=False),
    sa.Column('bar_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Double(), nullable=True),
    sa.Column('high', sa.Double(), nullable=True),
    sa.Column('low', sa.Double(), nullable=True),
    sa.Column('close', sa.Double(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'bar_date', name='uq_price_bars_ticker_date')
    )
    op.create_index(op.f('ix_price_bars_bar_date'), 'price_bars', ['bar_date'], unique=False)
    op.create_index(op.f('ix_price_bars_ticker'), 'price_bars', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_bars_ticker'), table_name='price_bars')
    op.drop_index(op.f('ix_price_bars_bar_date'), table_name='price_bars')
    op.drop_table('price_bars')
    # ### end Alembic commands ###
