"""initial_schema

Revision ID: 912506af2bea
Revises: 
Create Date: 2026-06-23 18:51:57.603618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '912506af2bea'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent', sa.String(length=100), nullable=False),
    sa.Column('ticker', sa.String(length=12), nullable=True),
    sa.Column('input_hash', sa.String(length=64), nullable=True),
    sa.Column('input_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_agent'), 'agent_runs', ['agent'], unique=False)
    op.create_index(op.f('ix_agent_runs_input_hash'), 'agent_runs', ['input_hash'], unique=False)
    op.create_index(op.f('ix_agent_runs_ticker'), 'agent_runs', ['ticker'], unique=False)
    op.create_table('news_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=12), nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('sentiment_score', sa.Double(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=True),
    sa.Column('event_weight', sa.Double(), nullable=True),
    sa.Column('news_score', sa.Double(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'source_url', name='uq_news_ticker_url')
    )
    op.create_index(op.f('ix_news_items_event_type'), 'news_items', ['event_type'], unique=False)
    op.create_index(op.f('ix_news_items_published_at'), 'news_items', ['published_at'], unique=False)
    op.create_index(op.f('ix_news_items_ticker'), 'news_items', ['ticker'], unique=False)
    op.create_table('scan_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tickers_scanned', sa.Integer(), nullable=True),
    sa.Column('tickers_flagged', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('params_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_universe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=200), nullable=True),
    sa.Column('market_cap', sa.BigInteger(), nullable=True),
    sa.Column('exchange', sa.String(length=20), nullable=True),
    sa.Column('ibkr_conid', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_refreshed', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_universe_ticker'), 'stock_universe', ['ticker'], unique=True)
    op.create_table('scan_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=12), nullable=False),
    sa.Column('scan_date', sa.Date(), nullable=False),
    sa.Column('composite_score', sa.Double(), nullable=True),
    sa.Column('volume_score', sa.Double(), nullable=True),
    sa.Column('momentum_score', sa.Double(), nullable=True),
    sa.Column('rs_score', sa.Double(), nullable=True),
    sa.Column('gap_score', sa.Double(), nullable=True),
    sa.Column('price', sa.Double(), nullable=True),
    sa.Column('volume_ratio', sa.Double(), nullable=True),
    sa.Column('pct_change_1d', sa.Double(), nullable=True),
    sa.Column('pct_change_5d', sa.Double(), nullable=True),
    sa.Column('pct_change_20d', sa.Double(), nullable=True),
    sa.Column('sma20', sa.Double(), nullable=True),
    sa.Column('sma50', sa.Double(), nullable=True),
    sa.Column('sma200', sa.Double(), nullable=True),
    sa.Column('rsi_14', sa.Double(), nullable=True),
    sa.Column('above_sma50', sa.Boolean(), nullable=True),
    sa.Column('above_sma200', sa.Boolean(), nullable=True),
    sa.Column('signals_fired', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['scan_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_results_run_id'), 'scan_results', ['run_id'], unique=False)
    op.create_index(op.f('ix_scan_results_scan_date'), 'scan_results', ['scan_date'], unique=False)
    op.create_index(op.f('ix_scan_results_ticker'), 'scan_results', ['ticker'], unique=False)
    op.create_table('stock_theses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=12), nullable=False),
    sa.Column('scan_result_id', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('why_interesting', sa.Text(), nullable=False),
    sa.Column('risk_factors', sa.Text(), nullable=False),
    sa.Column('sector_context', sa.Text(), nullable=True),
    sa.Column('peer_comparison', sa.Text(), nullable=True),
    sa.Column('news_summary', sa.Text(), nullable=True),
    sa.Column('catalysts', sa.Text(), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=True),
    sa.Column('news_score', sa.Double(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['scan_result_id'], ['scan_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_theses_ticker'), 'stock_theses', ['ticker'], unique=False)
    op.create_table('paper_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=12), nullable=False),
    sa.Column('thesis_id', sa.Integer(), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=True),
    sa.Column('entry_price', sa.Double(), nullable=True),
    sa.Column('target_price', sa.Double(), nullable=True),
    sa.Column('stop_price', sa.Double(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_by', sa.String(length=100), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('exit_date', sa.Date(), nullable=True),
    sa.Column('exit_price', sa.Double(), nullable=True),
    sa.Column('pnl', sa.Double(), nullable=True),
    sa.Column('pnl_pct', sa.Double(), nullable=True),
    sa.Column('hold_days', sa.Integer(), nullable=True),
    sa.Column('close_reason', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['thesis_id'], ['stock_theses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_trades_status'), 'paper_trades', ['status'], unique=False)
    op.create_index(op.f('ix_paper_trades_ticker'), 'paper_trades', ['ticker'], unique=False)
    op.create_table('watchlist_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=12), nullable=False),
    sa.Column('watchlist_date', sa.Date(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('composite_score', sa.Double(), nullable=True),
    sa.Column('scan_result_id', sa.Integer(), nullable=True),
    sa.Column('thesis_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scan_result_id'], ['scan_results.id'], ),
    sa.ForeignKeyConstraint(['thesis_id'], ['stock_theses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'watchlist_date', name='uq_watchlist_ticker_date')
    )
    op.create_index(op.f('ix_watchlist_entries_ticker'), 'watchlist_entries', ['ticker'], unique=False)
    op.create_index(op.f('ix_watchlist_entries_watchlist_date'), 'watchlist_entries', ['watchlist_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_entries_watchlist_date'), table_name='watchlist_entries')
    op.drop_index(op.f('ix_watchlist_entries_ticker'), table_name='watchlist_entries')
    op.drop_table('watchlist_entries')
    op.drop_index(op.f('ix_paper_trades_ticker'), table_name='paper_trades')
    op.drop_index(op.f('ix_paper_trades_status'), table_name='paper_trades')
    op.drop_table('paper_trades')
    op.drop_index(op.f('ix_stock_theses_ticker'), table_name='stock_theses')
    op.drop_table('stock_theses')
    op.drop_index(op.f('ix_scan_results_ticker'), table_name='scan_results')
    op.drop_index(op.f('ix_scan_results_scan_date'), table_name='scan_results')
    op.drop_index(op.f('ix_scan_results_run_id'), table_name='scan_results')
    op.drop_table('scan_results')
    op.drop_index(op.f('ix_stock_universe_ticker'), table_name='stock_universe')
    op.drop_table('stock_universe')
    op.drop_table('scan_runs')
    op.drop_index(op.f('ix_news_items_ticker'), table_name='news_items')
    op.drop_index(op.f('ix_news_items_published_at'), table_name='news_items')
    op.drop_index(op.f('ix_news_items_event_type'), table_name='news_items')
    op.drop_table('news_items')
    op.drop_index(op.f('ix_agent_runs_ticker'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_input_hash'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_agent'), table_name='agent_runs')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###
